# Database
spring:
  datasource:
    url: jdbc:h2:mem:exercise
    driverClassName: org.h2.Driver
    username: sa
    password: pw
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

# Data
dispatcher.id: 85e9f816-ebb3-4626-a684-17746f39eee3